config:
  d_tag_map:
          -30
  tag_z_min:
          0.01
  tag_z_max:
          0.015
  d_color_map:
          50
  color_z_min:
          0.01
  color_z_max:
          0.015
  d_color_y:
          20
  color_y_adjust:
          400
  center_x:
          340

#d_tag_map:  #如果标签夹取时前后位置不准，可调节此参数，调节间隔5，偏前+5，偏后-5
#tag_z_min:  ##如果标签夹取时较近的地方上下不准，可调节此参数，调节间隔0.005
#tag_z_max:  #如果标签夹取时较远的地方上下不准，可调节此参数，调节间隔0.005
#d_color_map:  #如果颜色夹取时刚下去时的位置不准，可调节此参数，调节时间隔5来调整，偏前+5，偏后-5
#color_z_min:  #如果颜色夹取时较近的地方上下不准，可调节此参数，调节时间隔0.005来调整
#color_z_max:  #如果颜色夹取时较远的地方上下不准，可调节此参数，调节时间隔0.005来调整
#d_color_y:  #如果颜色夹取时前后对不准，可调节此参数，调节间隔5，偏前+5，偏后-5
#color_y_adjust:  #如果颜色夹取时前后对不准，可调节此参数，调节间隔5，偏前+5，偏后-5
#center_x:  #如果夹取时左右对不准，可调节此参数，调节间隔5，偏左+5，偏右-5
