color_range_list:
  black:
    max:
    - 0
    - 227
    - 255
    min:
    - 0
    - 0
    - 0
  blue:
    max:
    - 169
    - 255
    - 104
    min:
    - 20
    - 0
    - 28
  green:
    max:
    - 189
    - 119
    - 154
    min:
    - 0
    - 0
    - 83
  red:
    max:
    - 129
    - 255
    - 238
    min:
    - 19
    - 132
    - 116
  white:
    max:
    - 56
    - 255
    - 255
    min:
    - 0
    - 0
    - 128
