controller_list:
  - name: fake_gripper_controller
    joints:
      - r_joint
  - name: fake_arm_controller
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
  - name: fake_camera_controller
    joints:
      []
initial:  # Define initial robot poses.
  - group: gripper
    pose: close
  - group: arm
    pose: p1